name: Terraform Azure Deploy

on:
  #push:
  #  branches:
  #    - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: dev
        type: choice
        options:
          - dev
          - sit
          - prod

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  TF_VAR_admin_username: ${{ secrets.TF_VAR_admin_username }}
  TF_VAR_ssh_public_key: ${{ secrets.TF_VAR_ssh_public_key }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    #strategy:
     # matrix:
     #   env: [dev]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Init
        working-directory: envs/${{ github.event.inputs.environment }}
        run: terraform init -input=false

      - name: Terraform Validate
        working-directory: envs/${{ github.event.inputs.environment }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: envs/${{ github.event.inputs.environment }}
        run: terraform plan -out=tfplan -input=false -lock=false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: envs/${{ github.event.inputs.environment }}
        run: terraform apply -input=false -auto-approve tfplan
